2024-05-18 14:27:38,703 INFO    MainThread:401934 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-05-18 14:27:38,703 INFO    MainThread:401934 [wandb_setup.py:_flush():76] Configure stats pid to 401934
2024-05-18 14:27:38,704 INFO    MainThread:401934 [wandb_setup.py:_flush():76] Loading settings from /users/eleves-a/2022/noam-joud-harold.ngoupeyou/.config/wandb/settings
2024-05-18 14:27:38,704 INFO    MainThread:401934 [wandb_setup.py:_flush():76] Loading settings from /Data/harold.ngoupeyou/cheese_classification_challenge/outputs/train/2024-05-18_14-27-37/wandb/settings
2024-05-18 14:27:38,704 INFO    MainThread:401934 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'entity': 'haroldng', 'project': 'cheese_classification_challenge', 'sweep_id': '7qgpihez', 'root_dir': '/Data/harold.ngoupeyou/cheese_classification_challenge', 'run_id': 'p9arzbdw', 'sweep_param_path': '/Data/harold.ngoupeyou/cheese_classification_challenge/wandb/sweep-7qgpihez/config-p9arzbdw.yaml'}
2024-05-18 14:27:38,704 INFO    MainThread:401934 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-18 14:27:38,704 INFO    MainThread:401934 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'train.py', 'program_abspath': '/Data/harold.ngoupeyou/cheese_classification_challenge/train.py', 'program': '/Data/harold.ngoupeyou/cheese_classification_challenge/train.py'}
2024-05-18 14:27:38,704 INFO    MainThread:401934 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-18 14:27:38,704 INFO    MainThread:401934 [wandb_init.py:_log_setup():520] Logging user logs to /Data/harold.ngoupeyou/cheese_classification_challenge/wandb/run-20240518_142738-p9arzbdw/logs/debug.log
2024-05-18 14:27:38,704 INFO    MainThread:401934 [wandb_init.py:_log_setup():521] Logging internal logs to /Data/harold.ngoupeyou/cheese_classification_challenge/wandb/run-20240518_142738-p9arzbdw/logs/debug-internal.log
2024-05-18 14:27:38,704 INFO    MainThread:401934 [wandb_init.py:init():560] calling init triggers
2024-05-18 14:27:38,704 INFO    MainThread:401934 [wandb_init.py:init():567] wandb.init called with sweep_config: {'datamodule.batch_size': 101, 'epochs': 35, 'optim.lr': 0.007605119438850357}
config: {}
2024-05-18 14:27:38,704 INFO    MainThread:401934 [wandb_init.py:init():610] starting backend
2024-05-18 14:27:38,704 INFO    MainThread:401934 [wandb_init.py:init():614] setting up manager
2024-05-18 14:27:38,711 INFO    MainThread:401934 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-05-18 14:27:38,712 INFO    MainThread:401934 [wandb_init.py:init():622] backend started and connected
2024-05-18 14:27:38,723 INFO    MainThread:401934 [wandb_run.py:_config_callback():1376] config_cb None None {'datamodule.batch_size': 101, 'epochs': 35, 'optim.lr': 0.007605119438850357}
2024-05-18 14:27:38,723 INFO    MainThread:401934 [wandb_init.py:init():711] updated telemetry
2024-05-18 14:27:38,726 INFO    MainThread:401934 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-05-18 14:27:39,094 INFO    MainThread:401934 [wandb_run.py:_on_init():2396] communicating current version
2024-05-18 14:27:39,223 INFO    MainThread:401934 [wandb_run.py:_on_init():2405] got version response 
2024-05-18 14:27:39,223 INFO    MainThread:401934 [wandb_init.py:init():795] starting run threads in backend
2024-05-18 14:27:41,969 INFO    MainThread:401934 [wandb_run.py:_console_start():2374] atexit reg
2024-05-18 14:27:41,969 INFO    MainThread:401934 [wandb_run.py:_redirect():2229] redirect: wrap_raw
2024-05-18 14:27:41,969 INFO    MainThread:401934 [wandb_run.py:_redirect():2294] Wrapping output streams.
2024-05-18 14:27:41,969 INFO    MainThread:401934 [wandb_run.py:_redirect():2319] Redirects installed.
2024-05-18 14:27:41,970 INFO    MainThread:401934 [wandb_init.py:init():838] run started, returning control to user process
2024-05-18 14:27:47,153 WARNING MsgRouterThr:401934 [router.py:message_loop():77] message_loop has been closed
